### PR TITLE
Rename `1ddpa_recursion.code'

### PR DESCRIPTION
**Pull request by leafac**
The code says it is actually `4ddpa'.

/cc @zepalmer

### CODE REVIEW

**Comment by leafac** [comment]
Closing this due to lack of feedback.

I'll sneak in this change on my `benchmark` Pull Request :smile:

**Comment by zepalmer** [comment]
I think we need to revisit the way we're managing these unit test source files in general.  One possibility would be to update [toy-language](https://github.com/JHU-PL-Lab/toy-language) to recursively search the directory for source files and to bring that downstream; then, Odefa could have a directory (or many directories) of analysis tests which are separate from the basic parser/interpreter functionality tests.  Right now, the DDPA prefix is just there to make it easy to find the analysis tests, which is a sort of crude approach.

**Comment by leafac** [comment]
I'm all in for that idea of organizing the tests in sub-directories. For the moment, I think at least we'd like the file names to be consistent with its contents. So I'm sneaking in the `benchmark` pull request the fixes for the inconsistently-named ones :smile:

**Comment by zepalmer** [comment]
Sounds good.

**Pull request closed without merging**
